Add plan-wide region variable to configure sunbeam region
canonical/sunbeam-terraform pull request #72
Opened 2024-05-10 08:36 UTC by gboutry

Requires: 
- [ ] https://review.opendev.org/c/openstack/sunbeam-charms/+/918972

2024-05-13 03:57 UTC, hemanthnakkina approved these changes

2024-05-13 04:07 UTC, hemanthnakkina requested changes
Add region to ceilometer config

2024-05-16 08:57 UTC, gboutry commented
force push is rebase on main

2024-05-17 11:57 UTC, hemanthnakkina approved these changes

2024-05-17 11:57 UTC, merged